### PR TITLE
use https so that emails work in dev

### PR DESCRIPTION
**Pull request by hardikshah7**

### CODE REVIEW

**Comment by jtrussell** [comment]
Auto decline.

**Comment by hardikshah7** [comment]
> Auto decline.

Wow! 😄

**Review by jtrussell — APPROVED** [review]

**Comment by lily-pytel** [comment]
🚃🚃🚃

**Review by evsheffield — CHANGES_REQUESTED** [review]
I'm a bit concerned that forcing HTTPS may result in issues in non-dev environments. For example, in our staging environment SSL is handled through the reverse proxy rather than on the server itself, and typically for the purpose of job queue requests we bypass the reverse proxy with a hosts file entry. Could you please test this change in a deployed environment?

If it does prove to be problematic in deployed environments, it might be nice to make it a configurable option so we can adjust it per environment. This also has the benefit that as an open-source project we don't make too many assumptions about people's server setups. :)

**Comment by hardikshah7** [comment]
@evsheffield  - I tested this in staging and the job queue requests completed successfully.

**Review by evsheffield — APPROVED** [review]

**Pull request merged**
